#pragma once

enum {
    USB_KEY_NONE =              0x00,

    USB_KEY_A =                 0x04,
    USB_KEY_B =                 0x05,
    USB_KEY_C =                 0x06,
    USB_KEY_D =                 0x07,
    USB_KEY_E =                 0x08,
    USB_KEY_F =                 0x09,
    USB_KEY_G =                 0x0A,
    USB_KEY_H =                 0x0B,
    USB_KEY_I =                 0x0C,
    USB_KEY_J =                 0x0D,
    USB_KEY_K =                 0x0E,
    USB_KEY_L =                 0x0F,
    USB_KEY_M =                 0x10,
    USB_KEY_N =                 0x11,
    USB_KEY_O =                 0x12,
    USB_KEY_P =                 0x13,
    USB_KEY_Q =                 0x14,
    USB_KEY_R =                 0x15,
    USB_KEY_S =                 0x16,
    USB_KEY_T =                 0x17,
    USB_KEY_U =                 0x18,
    USB_KEY_V =                 0x19,
    USB_KEY_W =                 0x1A,
    USB_KEY_X =                 0x1B,
    USB_KEY_Y =                 0x1C,
    USB_KEY_Z =                 0x1D,

    USB_KEY_1 =                 0x1E,
    USB_KEY_2 =                 0x1F,
    USB_KEY_3 =                 0x20,
    USB_KEY_4 =                 0x21,
    USB_KEY_5 =                 0x22,
    USB_KEY_6 =                 0x23,
    USB_KEY_7 =                 0x24,
    USB_KEY_8 =                 0x25,
    USB_KEY_9 =                 0x26,
    USB_KEY_0 =                 0x27,

    USB_KEY_ENTER =             0x28,
    USB_KEY_ESC =               0x29,
    USB_KEY_BACKSPACE =         0x2A,
    USB_KEY_TAB =               0x2B,
    USB_KEY_SPACE =             0x2C,
    USB_KEY_MINUS =             0x2D,
    USB_KEY_EQUAL =             0x2E,
    USB_KEY_LEFT_BRACE =        0x2F,
    USB_KEY_RIGHT_BRACE =       0x30,
    USB_KEY_BACKSLASH =         0x31,
    USB_KEY_NON_US_NUM =        0x32,
    USB_KEY_SEMICOLON =         0x33,
    USB_KEY_QUOTE =             0x34,
    USB_KEY_TILDE =             0x35,
    USB_KEY_COMMA =             0x36,
    USB_KEY_PERIOD =            0x37,
    USB_KEY_SLASH =             0x38,
    USB_KEY_CAPS_LOCK =         0x39,

    USB_KEY_F1 =                0x3A,
    USB_KEY_F2 =                0x3B,
    USB_KEY_F3 =                0x3C,
    USB_KEY_F4 =                0x3D,
    USB_KEY_F5 =                0x3E,
    USB_KEY_F6 =                0x3F,
    USB_KEY_F7 =                0x40,
    USB_KEY_F8 =                0x41,
    USB_KEY_F9 =                0x42,
    USB_KEY_F10 =               0x43,
    USB_KEY_F11 =               0x44,
    USB_KEY_F12 =               0x45,

    USB_KEY_PRINTSCREEN =       0x46,
    USB_KEY_SCROLL_LOCK =       0x47,
    USB_KEY_PAUSE =             0x48,
    USB_KEY_INSERT =            0x49,
    USB_KEY_HOME =              0x4A,
    USB_KEY_PAGE_UP =           0x4B,
    USB_KEY_DELETE =            0x4C,
    USB_KEY_END =               0x4D,
    USB_KEY_PAGE_DOWN =         0x4E,

    USB_KEY_RIGHT =             0x4F,
    USB_KEY_LEFT =              0x50,
    USB_KEY_DOWN =              0x51,
    USB_KEY_UP =                0x52,

    USB_KEY_NUM_LOCK =          0x53,
    USB_KEY_KEYPAD_SLASH =      0x54,
    USB_KEYPAD_ASTERIX =        0x55,
    USB_KEY_KEYPAD_MINUS =      0x56,
    USB_KEY_KEYPAD_PLUS =       0x57,
    USB_KEY_KEYPAD_ENTER =      0x58,
    USB_KEY_KEYPAD_1 =          0x59,
    USB_KEY_KEYPAD_2 =          0x5A,
    USB_KEY_KEYPAD_3 =          0x5B,
    USB_KEY_KEYPAD_4 =          0x5C,
    USB_KEY_KEYPAD_5 =          0x5D,
    USB_KEY_KEYPAD_6 =          0x5E,
    USB_KEY_KEYPAD_7 =          0x5F,
    USB_KEY_KEYPAD_8 =          0x60,
    USB_KEY_KEYPAD_9 =          0x61,
    USB_KEY_KEYPAD_0 =          0x62,
    USB_KEYPAD_PERIOD =         0x63,

    USB_KEY_NON_US_BACKSLASH =  0x64,
    USB_KEY_MENU =              0x65,
    USB_KEY_POWER =             0x66,
    USB_KEY_KEYPAD_EQUAL =      0x67,

    USB_KEY_F13 =               0x68,
    USB_KEY_F14 =               0x69,
    USB_KEY_F15 =               0x6A,
    USB_KEY_F16 =               0x6B,
    USB_KEY_F17 =               0x6C,
    USB_KEY_F18 =               0x6D,
    USB_KEY_F19 =               0x6E,
    USB_KEY_F20 =               0x6F,
    USB_KEY_F21 =               0x70,
    USB_KEY_F22 =               0x71,
    USB_KEY_F23 =               0x72,
    USB_KEY_F24 =               0x73,

    USB_KEY_HELP =              0x75,
    USB_KEY_MUTE =              0x7f,
    USB_KEY_VOLUME_UP =         0x80,
    USB_KEY_VOLUME_DOWN =       0x81,
};
