/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Mon Jan 28 21:43:08 2019. */

#include "messages-pairing.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t typesafely_protocol_pairing_ECDHPublicKey_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_pairing_ECDHPublicKey, public_key, public_key, 0),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_pairing_InitiatePairingRequest_fields[3] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, typesafely_protocol_pairing_InitiatePairingRequest, host_recognises_device_id, host_recognises_device_id, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, typesafely_protocol_pairing_InitiatePairingRequest, host_ecdh_public_key, host_recognises_device_id, &typesafely_protocol_pairing_ECDHPublicKey_fields),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_pairing_InitiatePairingResponse_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, typesafely_protocol_pairing_InitiatePairingResponse, device_ecdh_public_key, device_ecdh_public_key, &typesafely_protocol_pairing_ECDHPublicKey_fields),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_pairing_BeginAuthenticationRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_pairing_BeginAuthenticationResponse_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_pairing_CommitmentExchangeRequest_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_pairing_CommitmentExchangeRequest, host_commitment, host_commitment, 0),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_pairing_CommitmentExchangeResponse_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_pairing_CommitmentExchangeResponse, device_commitment, device_commitment, 0),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_pairing_NonceExchangeRequest_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_pairing_NonceExchangeRequest, host_nonce, host_nonce, 0),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_pairing_NonceExchangeResponse_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_pairing_NonceExchangeResponse, device_nonce, device_nonce, 0),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_pairing_ParameterConfirmationRequest_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_pairing_ParameterConfirmationRequest, host_parameter_confirmation, host_parameter_confirmation, 0),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_pairing_ParameterConfirmationResponse_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_pairing_ParameterConfirmationResponse, device_parameter_confirm, device_parameter_confirm, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(typesafely_protocol_pairing_InitiatePairingRequest, host_ecdh_public_key) < 65536 && pb_membersize(typesafely_protocol_pairing_InitiatePairingResponse, device_ecdh_public_key) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_typesafely_protocol_pairing_ECDHPublicKey_typesafely_protocol_pairing_InitiatePairingRequest_typesafely_protocol_pairing_InitiatePairingResponse_typesafely_protocol_pairing_BeginAuthenticationRequest_typesafely_protocol_pairing_BeginAuthenticationResponse_typesafely_protocol_pairing_CommitmentExchangeRequest_typesafely_protocol_pairing_CommitmentExchangeResponse_typesafely_protocol_pairing_NonceExchangeRequest_typesafely_protocol_pairing_NonceExchangeResponse_typesafely_protocol_pairing_ParameterConfirmationRequest_typesafely_protocol_pairing_ParameterConfirmationResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(typesafely_protocol_pairing_InitiatePairingRequest, host_ecdh_public_key) < 256 && pb_membersize(typesafely_protocol_pairing_InitiatePairingResponse, device_ecdh_public_key) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_typesafely_protocol_pairing_ECDHPublicKey_typesafely_protocol_pairing_InitiatePairingRequest_typesafely_protocol_pairing_InitiatePairingResponse_typesafely_protocol_pairing_BeginAuthenticationRequest_typesafely_protocol_pairing_BeginAuthenticationResponse_typesafely_protocol_pairing_CommitmentExchangeRequest_typesafely_protocol_pairing_CommitmentExchangeResponse_typesafely_protocol_pairing_NonceExchangeRequest_typesafely_protocol_pairing_NonceExchangeResponse_typesafely_protocol_pairing_ParameterConfirmationRequest_typesafely_protocol_pairing_ParameterConfirmationResponse)
#endif


/* @@protoc_insertion_point(eof) */
