/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Mon Jan 28 21:43:08 2019. */

#include "messages-connection.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t typesafely_protocol_connection_ConnectRequest_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_connection_ConnectRequest, id_host, id_host, 0),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_connection_ConnectResponse_fields[3] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, typesafely_protocol_connection_ConnectResponse, device_recognises_host_id, device_recognises_host_id, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, typesafely_protocol_connection_ConnectResponse, id_device, device_recognises_host_id, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
