/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Mon Jan 28 21:43:08 2019. */

#include "messages-session.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t typesafely_protocol_session_ECDHPublicKey_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_session_ECDHPublicKey, public_key, public_key, 0),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_session_OpenSessionRequest_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_session_OpenSessionRequest, host_authentication_data, host_authentication_data, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, typesafely_protocol_session_OpenSessionRequest, host_ecdh_public_key, host_authentication_data, &typesafely_protocol_session_ECDHPublicKey_fields),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_session_OpenSessionResponse_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, typesafely_protocol_session_OpenSessionResponse, device_authentication_data, device_authentication_data, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, typesafely_protocol_session_OpenSessionResponse, device_ecdh_public_key, device_authentication_data, &typesafely_protocol_session_ECDHPublicKey_fields),
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_session_UpgradeRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_session_UpgradeResponse_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t typesafely_protocol_session_Packet_fields[4] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, typesafely_protocol_session_Packet, sequence_num, sequence_num, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, typesafely_protocol_session_Packet, ciphertext, sequence_num, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, typesafely_protocol_session_Packet, tag, ciphertext, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(typesafely_protocol_session_OpenSessionRequest, host_ecdh_public_key) < 65536 && pb_membersize(typesafely_protocol_session_OpenSessionResponse, device_ecdh_public_key) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_typesafely_protocol_session_ECDHPublicKey_typesafely_protocol_session_OpenSessionRequest_typesafely_protocol_session_OpenSessionResponse_typesafely_protocol_session_UpgradeRequest_typesafely_protocol_session_UpgradeResponse_typesafely_protocol_session_Packet)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(typesafely_protocol_session_OpenSessionRequest, host_ecdh_public_key) < 256 && pb_membersize(typesafely_protocol_session_OpenSessionResponse, device_ecdh_public_key) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_typesafely_protocol_session_ECDHPublicKey_typesafely_protocol_session_OpenSessionRequest_typesafely_protocol_session_OpenSessionResponse_typesafely_protocol_session_UpgradeRequest_typesafely_protocol_session_UpgradeResponse_typesafely_protocol_session_Packet)
#endif


/* @@protoc_insertion_point(eof) */
