/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Mon Jan 28 21:43:08 2019. */

#ifndef PB_TYPESAFELY_PROTOCOL_SESSION_MESSAGES_SESSION_PB_H_INCLUDED
#define PB_TYPESAFELY_PROTOCOL_SESSION_MESSAGES_SESSION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _typesafely_protocol_session_UpgradeRequest {
    char dummy_field;
/* @@protoc_insertion_point(struct:typesafely_protocol_session_UpgradeRequest) */
} typesafely_protocol_session_UpgradeRequest;

typedef struct _typesafely_protocol_session_UpgradeResponse {
    char dummy_field;
/* @@protoc_insertion_point(struct:typesafely_protocol_session_UpgradeResponse) */
} typesafely_protocol_session_UpgradeResponse;

typedef PB_BYTES_ARRAY_T(32) typesafely_protocol_session_ECDHPublicKey_public_key_t;
typedef struct _typesafely_protocol_session_ECDHPublicKey {
    typesafely_protocol_session_ECDHPublicKey_public_key_t public_key;
/* @@protoc_insertion_point(struct:typesafely_protocol_session_ECDHPublicKey) */
} typesafely_protocol_session_ECDHPublicKey;

typedef PB_BYTES_ARRAY_T(8) typesafely_protocol_session_Packet_ciphertext_t;
typedef PB_BYTES_ARRAY_T(16) typesafely_protocol_session_Packet_tag_t;
typedef struct _typesafely_protocol_session_Packet {
    uint64_t sequence_num;
    typesafely_protocol_session_Packet_ciphertext_t ciphertext;
    typesafely_protocol_session_Packet_tag_t tag;
/* @@protoc_insertion_point(struct:typesafely_protocol_session_Packet) */
} typesafely_protocol_session_Packet;

typedef PB_BYTES_ARRAY_T(16) typesafely_protocol_session_OpenSessionRequest_host_authentication_data_t;
typedef struct _typesafely_protocol_session_OpenSessionRequest {
    typesafely_protocol_session_OpenSessionRequest_host_authentication_data_t host_authentication_data;
    typesafely_protocol_session_ECDHPublicKey host_ecdh_public_key;
/* @@protoc_insertion_point(struct:typesafely_protocol_session_OpenSessionRequest) */
} typesafely_protocol_session_OpenSessionRequest;

typedef PB_BYTES_ARRAY_T(16) typesafely_protocol_session_OpenSessionResponse_device_authentication_data_t;
typedef struct _typesafely_protocol_session_OpenSessionResponse {
    typesafely_protocol_session_OpenSessionResponse_device_authentication_data_t device_authentication_data;
    typesafely_protocol_session_ECDHPublicKey device_ecdh_public_key;
/* @@protoc_insertion_point(struct:typesafely_protocol_session_OpenSessionResponse) */
} typesafely_protocol_session_OpenSessionResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define typesafely_protocol_session_ECDHPublicKey_init_default {{0, {0}}}
#define typesafely_protocol_session_OpenSessionRequest_init_default {{0, {0}}, typesafely_protocol_session_ECDHPublicKey_init_default}
#define typesafely_protocol_session_OpenSessionResponse_init_default {{0, {0}}, typesafely_protocol_session_ECDHPublicKey_init_default}
#define typesafely_protocol_session_UpgradeRequest_init_default {0}
#define typesafely_protocol_session_UpgradeResponse_init_default {0}
#define typesafely_protocol_session_Packet_init_default {0, {0, {0}}, {0, {0}}}
#define typesafely_protocol_session_ECDHPublicKey_init_zero {{0, {0}}}
#define typesafely_protocol_session_OpenSessionRequest_init_zero {{0, {0}}, typesafely_protocol_session_ECDHPublicKey_init_zero}
#define typesafely_protocol_session_OpenSessionResponse_init_zero {{0, {0}}, typesafely_protocol_session_ECDHPublicKey_init_zero}
#define typesafely_protocol_session_UpgradeRequest_init_zero {0}
#define typesafely_protocol_session_UpgradeResponse_init_zero {0}
#define typesafely_protocol_session_Packet_init_zero {0, {0, {0}}, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define typesafely_protocol_session_ECDHPublicKey_public_key_tag 1
#define typesafely_protocol_session_Packet_sequence_num_tag 1
#define typesafely_protocol_session_Packet_ciphertext_tag 2
#define typesafely_protocol_session_Packet_tag_tag 3
#define typesafely_protocol_session_OpenSessionRequest_host_authentication_data_tag 1
#define typesafely_protocol_session_OpenSessionRequest_host_ecdh_public_key_tag 2
#define typesafely_protocol_session_OpenSessionResponse_device_authentication_data_tag 1
#define typesafely_protocol_session_OpenSessionResponse_device_ecdh_public_key_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t typesafely_protocol_session_ECDHPublicKey_fields[2];
extern const pb_field_t typesafely_protocol_session_OpenSessionRequest_fields[3];
extern const pb_field_t typesafely_protocol_session_OpenSessionResponse_fields[3];
extern const pb_field_t typesafely_protocol_session_UpgradeRequest_fields[1];
extern const pb_field_t typesafely_protocol_session_UpgradeResponse_fields[1];
extern const pb_field_t typesafely_protocol_session_Packet_fields[4];

/* Maximum encoded size of messages (where known) */
#define typesafely_protocol_session_ECDHPublicKey_size 34
#define typesafely_protocol_session_OpenSessionRequest_size 54
#define typesafely_protocol_session_OpenSessionResponse_size 54
#define typesafely_protocol_session_UpgradeRequest_size 0
#define typesafely_protocol_session_UpgradeResponse_size 0
#define typesafely_protocol_session_Packet_size  39

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_SESSION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
